### ISSUE TITLE
Ignore warnings when exporting a MobX observer component

### ISSUE THREAD

**Issue by HorusGoul** [ArnaudBarre/eslint-plugin-react-refresh#59]
Like #51, the `mobx-react-lite` works with high order components to connect components to MobX stores.

See the docs: https://mobx.js.org/react-integration.html

**Workaround**
As a workaround, I patched the package to add `observer` to the `reactHOCs` list: 
https://github.com/ArnaudBarre/eslint-plugin-react-refresh/blob/ba9bb7b8915e338749a68f3676f8d37defe4f87c/src/only-export-components.ts#L301

**Ideal solution**
A way to configure additional HOCs.

**Comment by ArnaudBarre** [comment]
Seems like a legit usecase. Instead of adding it directly, I think a new option make sens here for others/future librairies with similar pattern.

I'll keep it in my backlog, but if you want to contribute, feel free to send a PR similar to https://github.com/ArnaudBarre/eslint-plugin-react-refresh/pull/55/files?w=1!
