### ISSUE TITLE
Suggestion: switch recommended severity from "warn" to "error"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ArnaudBarre/eslint-plugin-react-refresh#65]
Per https://github.com/eslint/eslint/issues/16696 ->  https://eslint.org/docs/latest/use/configure/rules#rule-severities, ESLint's recommendation is to set rules to `"error"`. IME when something is only a warning then folks tend to leave it in over time. That adds to visual clutter in editor & lint runs, and even worse, trains devs to be ok with squiggly complaints.

Proposal: would you be open to switching the severity suggestion in docs from `"warn"` to `"error"`?

This is also relevant for #64, wherein the exported config from the plugin actually would contain the severity.

**Comment by ArnaudBarre** [comment]
Yeah that's one of the decision decision of ESLint that I don't like: the concept of warning being "ok"

Because in the past I add a bit too much of lint rules being stylistic, I liked the idea from CRA to have warning by default and error only when the code will not be able to run. And my lint command contains `--max-warnings 0` in all my projects to compensate that.

That's sad that ESLint shipped two types of warning put didn't enforce the second one, and decided to keep both but advice people to use only one...

Even if this is super bias, because of the impact CRA had on the community, I'm curious if people use more warn or error by default. If Bluesky add support for pool it could be a nice one to make

That's also one reason I liked the idea to not ship the config, it let people choose what they want.

Anyway I think aligning with ESLint/TS-ESLint recommandations is probably better

**Comment by JoshuaKGoldberg** [comment]
Yeah 🙃 this keeps coming up. I think we're in agreement. My personal framing that _within_ ESLint, it should all be "error" levels (`--max-warnings 0`), but _outside_ ESLint it should never block a build. I also set ESLint squigglies in my editor to yellow so they're disambiguated them from red TypeScript squigglies.
